log/urls.py
from django.conf.urls import url
from . import views

# We are adding a URL called /home
urlpatterns = [
    # url(r'^$', views.home, name='home'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('tutorapp.urls')),
    url(r'', include('timepost.urls')),
]

log/models.py
from django.db import models
from django.contrib.auth.models import User
from tutorapp.course_list import COURSE_CHOICES
from tutorapp.year_level import YEAR_LEVEL
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MinValueValidator, MaxValueValidator


#user_profile_id = models.AutoField(primary_key = True)
# Create your models here.

class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    major = models.CharField(max_length=20, choices=COURSE_CHOICES,
                             default='CPSC')
    year_level = models.IntegerField(choices=YEAR_LEVEL, default=1)
    rating = models.DecimalField(max_digits=5, decimal_places=2, default=0.00,validators=[MinValueValidator(0.00), MaxValueValidator(10.00)])
    number_of_votes = models.IntegerField(default = 0)

    # user_profile_id = models.AutoField(primary_key = True)

    def update_profile(request, user_id):
        user = User.objects.get(pk=user_id)
        user.save()

        # def save(self, *args, **kwargs):
        #     u = super(User, self).save(*args, **kwargs)
        #     UserProfile.objects.get_or_create(user_id=u.id)
        #     return u

        @receiver(post_save, sender=User)
        def create_user_profile(
            sender,
            instance,
            created,
            **kwargs
            ):
            if create:
                UserProfile.objects.create(user=instance)

        @receiver(post_save, sender=User)
        def save_user_profile(sender, instance, **kwargs):
            instance.user_profile.save()

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>MentorUs</title>
            <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
            <link rel="stylesheet" href="{% static 'css/login.css' %}">
            <link rel="stylesheet" href="{% static 'css/home.css' %}">
            <link rel="stylesheet" href="{% static 'css/register.css' %}">
            <link rel="stylesheet" href="{% static 'css/post_edit.css' %}">
            <link rel="stylesheet" href="{% static 'css/post_list.css' %}">
            <link rel="stylesheet" href="{% static 'css/post_detail.css' %}">
            <!-- Font Download -->
            <link href="https://fonts.googleapis.com/css?family=Raleway:300|Questrial|Poiret+One" rel="stylesheet">
            <!-- Time picker -->
            <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
            <script src = "{% static 'css/jquery.timepicker.min.css' %}"></script>
            <script src = "{% static 'js/jquery.min.js' %}"></script>
            
            <script type='text/javascript' src="{% static 'js/jquery.timepicker.min.js' %}"></script>
            <script type='text/javascript' src="{% static 'js/post_edit.js' %}"></script>
            <script type='text/javascript' src="{% static 'js/post_detail.js' %}"></script>
            <script type='text/javascript' src="{% static 'js/home.js' %}"></script>
            <script type='text/javascript' src="{% static 'js/post_list3.js' %}"></script>
            <script src = "{% static 'js/bootstrap.min.js' %}"></script>



    </head>
    
    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" >
                        <span class="sr-only">Toggle navigation</span>
                    </button>
                    <a class="navbar-brand" style= "color: DarkCyan" href="/#">MentorUs</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" style = "color:DarkCyan">Menu
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="/">Home</a>
                                </li>
                                {%  if user.pk is None %}
                                    <li>
                                        <a href="/login">Login</a>
                                    </li>
                                    <li>
                                        <a href="/register">Register</a>
                                    </li>
                                {% endif %}
                                {% if not user.pk is None %}

                                    <li class="divider"></li>
                                    <li>
                                        <a href="{% url "post_new" %}">Add New Post</a>
{#                                    </li>#}
{#                                    <li class="divider"></li>#}
{#                                    <li>#}
{#                                    <a href="/post">Post List</a>#}
{#                                    </li>#}
                                    <li class="divider"></li>
                                    <li>
                                        <a href="{% url 'my_post' %}">My Posts</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="/update">Update Profile</a>
                                    </li>
                                    <li class="divider"></li>
                                    <li>
                                        <a href="/logout">Logout</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    {% block content %}
    {% endblock %}

    {% block javascript %}
    {% endblock %}

    </body>
</html>

templates/form.html
{% extends "base.html" %}


{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>{{ title }}</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form }}
<input type='submit' class='btn btn-default' value='{{ title }}' />
</form>
</div>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
          <div class = "col-container">
            <div class="col-md-6">
                <div class = "jumbotron">
                {% if not user.pk is None %}
                    <h4>Hello:{{ user.get_full_name }}</h4>
                    <ul>
                        <li>Username: {{ user.username }}</li>
                        <li>Email: {{ user.email }}</li>
                        <li>Year level: {{ user.userprofile.year_level }}</li>
                        <li>Major: {{ user.userprofile.major }}</li>
                        <li>Rating: {{ user.userprofile.rating }}</li>
                    </ul>

                    <a href="{% url 'post_new' %}" class="btn btn-info btn-lg" id="addpost"><span class="glyphicon glyphicon-plus"></span> add new tutor </a>


                {% else %}
                   

                    <h4> Welcome to MentorUs </h4>  
                    <h5> <i> "your instant access to the nearest tutor" </i> </h5>
                    </br>
                    </br>


                     <a href="{% url 'login' %}" class="btn btn-md"> Login </a>

                    <a href="{% url 'register' %}" class="btn btn-md "> Register </a>

                {% endif %}

                
                
            </div>
            </div>

            <div class="col-md-6">
                <form class="form-group">

                {{ form.as_p }}

                <button type="submit" class="save btn btn-default"><span class="glyphicon glyphicon-search" > </span> Search</button>

                </form>
            </div>
        </div>

    </div>
</div>




{% endblock %}

templates/login.html
{% extends 'base.html' %}


{% block content %}
    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    {% if next %}
        {% if user.is_authenticated %}
            <p>Your account doesn't have access to this page. To proceed,
                please login with an account that has access.</p>
        {% else %}

            <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                 <!--    <center> -->
                        <h3 class="panel-title">. . . sign in</h3>
             <!--        </center> -->
                    </div>
                 <!--    <center> -->
                    <div class="panel-body">
                        <form method="post" action="{% url 'login' %}">
                        {% csrf_token %}

                            <p class="bs-component">
                                <table>
                                    <tr>
                                        <td>{{ form.username.label_tag }} </td>
                                    </tr>
                                    <tr>
                                        <td>{{ form.username }}</td>
                                    </tr>
                                    <tr>
                                        <td>{{ form.password.label_tag }}</td>
                                    </tr>
                                    <tr>
                                        <td>{{ form.password }}</td>
                                    </tr>
                                </table>
                            </p>
                            <p class="bs-component1">

                                    <input class="btn btn-success btn-sm" type="submit" value="login" />

                            </p>
                            <input type="hidden" name="next" value="{{ next }}" />
                        </form>
                    </div>
                   <!--  </center> -->
                </div>
            </div>
        </div>
        <!-- <div class ="Title">
            <h1> tutor app </h1>
        </div> -->
    </div>

    


{% endblock %}

{% block javascript %}


{% endblock %}

templates/my_post.html
{% extends 'base.html' %}

{% block content %}
    {% if message %}
        <div class=""><p>{{ message }}</p></div>
    {% endif %}
    <div>
        <table class="table table-hover"  id= "post_table">
            <thead>
            <tr>
                <th>Created Date</th>
                <th>Course</th>
                <th>User Name</th>
                <th>Year</th>
                <th>Name</th>
                <th>Details</th>
            </tr>
            </thead>
            <tbody>
            {% for post in posts %}
                <tr>
                <td>{{ post.created_at }}</td>
                <td>{{ post.course_name }} {{ post.course_number }}</td>
                <td>{{ post.username }}</td>
                <td>{{ post.year }}</td>
                <td>{{ post.name }}</td>
{#                <td>{{ post.user.get_fullname }}</td>#}
                <td><a href="{% url 'post_detail' pk=post.pk %}"> Detail </a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    
    <a class="btn btn-default" href="{% url 'post_filter' %}" id="button_filter">Filter</a>

    <a href="{% url 'post_new' %}" class="btn btn-info btn-lg" id="addclass"><span class="glyphicon glyphicon-plus-sign"></span> add new class </a>
{% endblock %}

templates/post_detail.html
{% extends 'base.html' %}



{% block content %}
    <div class = "post-detail-body">
            <div class="panel-detail panel-default" >
                <div class="post-detail panel-heading" >
                    Created at: {{ post.created_at }}
                </div>

                <div class="post-detail panel-body">
                    {% if author.pk != 'error' %}
                    UserName: {{ author.user.get_username }}<br>
                    Name: {{ author.user.get_full_name }}<br>
                    Year: {{ author.get_year_level_display }}<br>
                    Major: {{ author.get_major_display }}<br>
                    Course: {{ post.course_name }} {{ post.course_number }}<br>
                    Start At: {{ post.start_at }}<br>
                    End At: {{ post.end_at }}<br>
                    Comment: {{ post.comment }} <br>

                    {% else %}
                    Invalid operation

                    {% endif %}
                </div>






                <button type = "button" class = "btn email" data-toggle="modal" data-target="#myModalPostDetail">Send Email</button>
                {% if author.user.pk is user.pk %}
                    <a href="{% url 'post_edit' pk=post.pk %}" class="btn email" id="editclass"><span class="glyphicon glyphicon-pencil"></span> Edit </a>
                    <a href="{% url 'post_delete' pk=post.pk prev=request.META.HTTP_REFERER %}" class="btn email" id="editclass"><span class="glyphicon glyphicon-remove"></span> Delete </a>
                {% endif %}
             </div>

             </div>

                <div id="myModalPostDetail" class="modal fade" role="dialog">
                    <div class = "modal-dialog modal-sm">
                        <div class="modal-content">
                            <div class = "modal-body">
                              <h4 class = "modal-post-detail-title"> Send Email to the tutor? </h4>
                            </div>
                            <div class = "modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal"><span class = "glyphicon glyphicon-remove"></span></button>
                                <button type="button" class="btn btn-primary"><span class = "glyphicon glyphicon-send"></span></button>
                            </div>
                        </div>
                    </div>

            </div>

   
{% endblock %}

templates/post_edit.html
{% extends 'base.html' %}

{% block content %}
    <div class = "postedit_title">
    <h1>New post</h1>
    </div>
    
    <div class = "postedit_body">
	    <form method="POST" class="post-form">

            <div class="newPostDetail">
                {% csrf_token %}
                {# Form created through python. Contains details about tutoring course details #}
                {{ form.as_p }}
{#                <button class="save btn btn-default" id="newPostNext">Next</button>#}
            </div>
            <button class="save btn btn-default" id="newPostSave">Save</button>
	    </form>

            {#DOM for users to choose dates#}

            <div id = "Availability">
            <h4> Availability: </h4>
                <button class="add_tutor_time">Add Time</button>
            </div>


{#            <div class = "checkbox">#}
{#                 <label id = "monday" ><input type="checkbox" value="" class="daysofweek"> MONDAY</label>#}
{#                 <input class="timepicker text-center"  jt-timepicker="" time="model.time" time-string="model.timeString" default-time="model.options.defaultTime" time-format="model.options.timeFormat" start-time="model.options.startTime" min-time="model.options.minTime" max-time="model.options.maxTime" interval="model.options.interval" dynamic="model.options.dynamic" scrollbar="model.options.scrollbar" dropdown="model.options.dropdown" placeholder="start time" id = "mondaystart">#}
{#                <input class="timepicker text-center" jt-timepicker="" time="model.time" time-string="model.timeString" default-time="model.options.defaultTime" time-format="model.options.timeFormat" start-time="model.options.startTime" min-time="model.options.minTime" max-time="model.options.maxTime" interval="model.options.interval" dynamic="model.options.dynamic" scrollbar="model.options.scrollbar" dropdown="model.options.dropdown" placeholder="end time" id = "mondayend">#}
{#            </div>#}
{##}
{#            <div class = "checkbox">#}
{#                <label id = "tuesday"><input type="checkbox" value=""  class="daysofweek"> TUESDAY</label>#}
{#                <input class="timepicker text-center"  jt-timepicker="" time="model.time" time-string="model.timeString" default-time="model.options.defaultTime" time-format="model.options.timeFormat" start-time="model.options.startTime" min-time="model.options.minTime" max-time="model.options.maxTime" interval="model.options.interval" dynamic="model.options.dynamic" scrollbar="model.options.scrollbar" dropdown="model.options.dropdown" placeholder="start time">#}
{#                <input class="timepicker text-center" jt-timepicker="" time="model.time" time-string="model.timeString" default-time="model.options.defaultTime" time-format="model.options.timeFormat" start-time="model.options.startTime" min-time="model.options.minTime" max-time="model.options.maxTime" interval="model.options.interval" dynamic="model.options.dynamic" scrollbar="model.options.scrollbar" dropdown="model.options.dropdown" placeholder="end time">#}
{#            </div>#}
{##}
{#            <div class = "checkbox">#}
{#                 <label id = "wednesday"><input type="checkbox" value="" class="daysofweek"> WEDNESDAY</label>#}
{#                 <input class="timepicker text-center"  jt-timepicker="" time="model.time" time-string="model.timeString" default-time="model.options.defaultTime" time-format="model.options.timeFormat" start-time="model.options.startTime" min-time="model.options.minTime" max-time="model.options.maxTime" interval="model.options.interval" dynamic="model.options.dynamic" scrollbar="model.options.scrollbar" dropdown="model.options.dropdown" placeholder="start time">#}
{#                <input class="timepicker text-center" jt-timepicker="" time="model.time" time-string="model.timeString" default-time="model.options.defaultTime" time-format="model.options.timeFormat" start-time="model.options.startTime" min-time="model.options.minTime" max-time="model.options.maxTime" interval="model.options.interval" dynamic="model.options.dynamic" scrollbar="model.options.scrollbar" dropdown="model.options.dropdown" placeholder="end time">#}
{#            </div>#}
{##}
{#            <div class = "checkbox">#}
{#                 <label id = "thursday"><input type="checkbox" value="" class="daysofweek"> THURSDAY</label>#}
{#                 <input class="timepicker text-center"  jt-timepicker="" time="model.time" time-string="model.timeString" default-time="model.options.defaultTime" time-format="model.options.timeFormat" start-time="model.options.startTime" min-time="model.options.minTime" max-time="model.options.maxTime" interval="model.options.interval" dynamic="model.options.dynamic" scrollbar="model.options.scrollbar" dropdown="model.options.dropdown" placeholder="start time">#}
{#                <input class="timepicker text-center" jt-timepicker="" time="model.time" time-string="model.timeString" default-time="model.options.defaultTime" time-format="model.options.timeFormat" start-time="model.options.startTime" min-time="model.options.minTime" max-time="model.options.maxTime" interval="model.options.interval" dynamic="model.options.dynamic" scrollbar="model.options.scrollbar" dropdown="model.options.dropdown" placeholder="end time">#}
{#            </div>#}
{##}
{#            <div class = "checkbox">#}
{#                 <label id = "friday"><input type="checkbox" value="" class="daysofweek"> FRIDAY</label>#}
{#                <input class="timepicker text-center"  jt-timepicker="" time="model.time" time-string="model.timeString" default-time="model.options.defaultTime" time-format="model.options.timeFormat" start-time="model.options.startTime" min-time="model.options.minTime" max-time="model.options.maxTime" interval="model.options.interval" dynamic="model.options.dynamic" scrollbar="model.options.scrollbar" dropdown="model.options.dropdown" placeholder="start time">#}
{#                <input class="timepicker text-center" jt-timepicker="" time="model.time" time-string="model.timeString" default-time="model.options.defaultTime" time-format="model.options.timeFormat" start-time="model.options.startTime" min-time="model.options.minTime" max-time="model.options.maxTime" interval="model.options.interval" dynamic="model.options.dynamic" scrollbar="model.options.scrollbar" dropdown="model.options.dropdown" placeholder="end time">#}
{#            </div>#}
{#            <div class = "checkbox">#}
{#                 <label id = "saturday"><input type="checkbox" value="" class="daysofweek"> SATURDAY</label>#}
{#                <input class="timepicker text-center"  jt-timepicker="" time="model.time" time-string="model.timeString" default-time="model.options.defaultTime" time-format="model.options.timeFormat" start-time="model.options.startTime" min-time="model.options.minTime" max-time="model.options.maxTime" interval="model.options.interval" dynamic="model.options.dynamic" scrollbar="model.options.scrollbar" dropdown="model.options.dropdown" placeholder="start time">#}
{#                <input class="timepicker text-center" jt-timepicker="" time="model.time" time-string="model.timeString" default-time="model.options.defaultTime" time-format="model.options.timeFormat" start-time="model.options.startTime" min-time="model.options.minTime" max-time="model.options.maxTime" interval="model.options.interval" dynamic="model.options.dynamic" scrollbar="model.options.scrollbar" dropdown="model.options.dropdown" placeholder="end time">#}
{#            </div>#}
{##}
{#            <div class = "checkbox">#}
{#                 <label id= "sunday"><input type="checkbox" value="" class="daysofweek"> SUNDAY</label>#}
{#                 <input class="timepicker text-center"  jt-timepicker="" time="model.time" time-string="model.timeString" default-time="model.options.defaultTime" time-format="model.options.timeFormat" start-time="model.options.startTime" min-time="model.options.minTime" max-time="model.options.maxTime" interval="model.options.interval" dynamic="model.options.dynamic" scrollbar="model.options.scrollbar" dropdown="model.options.dropdown" placeholder="start time">#}
{#                <input class="timepicker text-center" jt-timepicker="" time="model.time" time-string="model.timeString" default-time="model.options.defaultTime" time-format="model.options.timeFormat" start-time="model.options.startTime" min-time="model.options.minTime" max-time="model.options.maxTime" interval="model.options.interval" dynamic="model.options.dynamic" scrollbar="model.options.scrollbar" dropdown="model.options.dropdown" placeholder="end time">#}
{#            </div>#}

{#            <button class="save btn btn-default" id="backToDetail">Back</button>#}

    </div>
{% endblock %}

templates/post_list.html
{% extends 'base.html' %}

{% block content %}
    {% if message %}
        <div class=""><p>{{ message }}</p></div>
    {% endif %}
    <div>
        <table class="table table-hover"  id= "post_table">
            <thead>
            <tr>
                <th>Created Date</th>
                <th>Course</th>
                <th>User Name</th>
                <th>Year</th>
                <th>Name</th>
                <th>Details</th>
            </tr>
            </thead>
            <tbody>
            {% for pair in posts %}
                <tr>
                <td>{{ pair.post.created_at }}</td>
                <td>{{ pair.post.course_name }} {{ pair.post.course_number }}</td>
                <td>{{ pair.author.user.get_username }}</td>
                <td>{{ pair.author.get_year_level_display }}</td>
                <td>{{ pair.author.user.get_full_name }}</td>
                <td><a href="{% url 'post_detail' pk=pair.post.pk %}"> Detail </a></td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{#    TODO: This part should be discussed#}
{#    {% if not request.user.is_authenticated %}#}
{#    <div id="myModalLogin" class="modal fade" role="dialog">#}
{#            <div class = "modal-dialog">#}
{#                  <div class="modal-content login">#}
{#                      <div class = "modal-body">#}
{##}
{##}
{##}
{##}
{#                         <div class = "login-panel panel">#}
{#                            <div class = "panel-heading">#}
{#                                <h3 class = "panel-title modal-login"> Sign In to Continue </h3>#}
{#                            </div>#}
{#                            <div class = "panel-body">#}
{##}
{#                              <form action="{% url 'login' %}" method="post" class = "modal-login">#}
{#                                {% csrf_token %}#}
{#                                <table>#}
{#                                    <tr> <td> <label for = "id_username">#}
{#                                        Username: </label> </td></tr>#}
{##}
{#                                    <tr> <td><input type = "text" name = "username" required id = "id_username"></td></tr>#}
{##}
{#                                    <tr> <td> <label for ="id_password"> Password: </label></td></tr>#}
{##}
{#                                    <tr><td><input type = "password" name = "password" required id = "id_password"> </td></tr>#}
{##}
{#                                </table>#}
{##}
{#                                </br>#}
{#                                <div class="btn-modal-login">#}
{#                                 <input class="btn btn-success btn-sm " id = "modalbutton" type="submit" value="login" />#}
{##}
{#                                 </div >#}
{##}
{#                                <a href="{% url 'register' %}" class="btn btn-modal-register "> Register </a>#}
{##}
{#                                     <input type="hidden" name="next" value="{{ next }}" />#}
{##}
{#                                </form>#}
{##}
{##}
{##}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{##}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#    {% endif %}#}



{% endblock %}

templates/post_list3.html
{% extends 'base.html' %}

{% block content %}
    {% if message %}
        <div class=""><p>{{ message }}</p></div>
    {% endif %}
    <div>
        <table class="table table-hover"  id= "post_table">
            <thead>
            <tr>
                <th>Created Date</th>
                <th>Course</th>
                <th>User Name</th>
                <th>Year</th>
                <th>Name</th>
                <th>Details</th>
            </tr>
            </thead>
            <tbody>
            {% for post in posts %}
                <tr>
                <td>{{ post.created_at }}</td>
                <td>{{ post.course_name }} {{ post.course_number }}</td>
                <td>{{ post.username }}</td>
                <td>{{ post.year }}</td>

                <td>{{ post.name }}</td>
                <td><a href="{% url 'post_detail' pk=post.pk %}"> Detail </a></td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>


    <div id="myModalLogin" class="modal fade" role="dialog">
            <div class = "modal-dialog">
                  <div class="modal-content login">
                      <div class = "modal-body">
                      


                      
                         <div class = "login-panel panel">
                            <div class = "panel-heading">
                                <h3 class = "panel-title modal-login"> Sign In to Continue </h3>
                            </div>
                            <div class = "panel-body">

                              <form action="{% url 'login' %}" method="post" class = "modal-login">
                                {% csrf_token %}
                                <table>
                                    <tr> <td> <label for = "id_username">
                                        Username: </label> </td></tr>

                                    <tr> <td><input type = "text" name = "username" required id = "id_username"></td></tr>

                                    <tr> <td> <label for ="id_password"> Password: </label></td></tr>

                                    <tr><td><input type = "password" name = "password" required id = "id_password"> </td></tr>

                                </table>

                                </br>
                                <div class="btn-modal-login">
                                 <input class="btn btn-success btn-sm " id = "modalbutton" type="submit" value="login" />

                                 </div >

                                <a href="{% url 'register' %}" class="btn btn-modal-register "> Register </a>

                                     <input type="hidden" name="next" value="{{ next }}" />
                        
                                </form>

                                
                            
                            </div>
                        </div>
                    </div>

            </div>
        </div>
    </div>


    <a href="{% url 'post_new' %}" class="btn btn-info btn-lg" id="addpost"><span class="glyphicon glyphicon-plus"></span> add new post </a>
{% endblock %}

templates/post_search.html
{% extends 'base.html' %}

{% block content %}
    <div class = "postedit_title">
    <h1>New post</h1>
    </div>

    <div class = "postedit_body">
	    <form class="post-form">

	        {{ form.as_p }}

	        <button type="submit" class="save btn btn-default">Search</button>
	    </form>
    </div>
{% endblock %}

templates/register.html
{% extends "base.html" %}


{% block content %}
<div class='col-sm-6 col-sm-offset-3'>

<div class = "RegisterTitle">
	<h1>. . . {{ title }}</h1>
</div>
<hr/>

	<div class = "content">
		<div class = "register-form">
			<form class="form-group column" method='POST' action='' enctype='multipart/form-data'>
			{% csrf_token %}
			<div class="form-inline">
				{{ user_form.as_table |linebreaks }}
				{{ profile_form.as_table | linebreaks }}	
			</div>
			</br>
			<input type='submit' class='btn btn-default' value='{{ title }}' />
			</form>
		</div>
	</div>
</div>
{% endblock content %}